name: 01 - Trigger and Parameter Extraction

on:
  issues:
    types: [opened]

# 添加权限配置
permissions:
  issues: write
  contents: read

jobs:
  trigger:
    runs-on: ubuntu-latest
    outputs:
      trigger_output: ${{ toJson(steps.setup.outputs.data) }}
      trigger_type: ${{ steps.setup.outputs.trigger_type }}
      build_id: ${{ steps.setup.outputs.build_id }}
    steps:
      - name: Setup framework
        id: setup
        run: |
          echo "Preparing environment..."
          
          # 判断触发方式并提取参数
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            # 手动触发：使用workflow_dispatch输入参数
            echo "Manual trigger detected"
            TRIGGER_TYPE="workflow_dispatch"
            BUILD_ID="${{ github.run_id }}"
            TAG="${{ github.event.inputs.tag }}"
            EMAIL="${{ github.event.inputs.email }}"
            CUSTOMER="${{ github.event.inputs.customer }}"
            CUSTOMER_LINK="${{ github.event.inputs.customer_link }}"
            SUPER_PASSWORD="${{ github.event.inputs.super_password }}"
            SLOGAN="${{ github.event.inputs.slogan }}"
            RENDEZVOUS_SERVER="${{ github.event.inputs.rendezvous_server }}"
            RS_PUB_KEY="${{ github.event.inputs.rs_pub_key }}"
            API_SERVER="${{ github.event.inputs.api_server }}"
          else
            # Issue触发：从issue内容中提取参数
            echo "Issue trigger detected"
            TRIGGER_TYPE="issue"
            BUILD_ID="${{ github.event.issue.number }}"
            ISSUE_BODY="${{ github.event.issue.body }}"
            
            # 保存原始issue内容供后续使用
            echo "ORIGINAL_ISSUE_BODY=$ISSUE_BODY" >> $GITHUB_ENV
            
            # 使用grep和sed提取参数值 - 支持多种格式
            # 格式1: tag: 值 (新格式)
            # 格式2: --tag: 值 (旧格式)
            # 格式3: tag=值 (键值对格式)
            TAG=$(echo "$ISSUE_BODY" | grep -oP '(?:^|\n)(?:--)?tag:\s*\K[^\r\n]+' | head -1 || echo "")
            EMAIL=$(echo "$ISSUE_BODY" | grep -oP '(?:^|\n)(?:--)?email:\s*\K[^\r\n]+' | head -1 || echo "")
            CUSTOMER=$(echo "$ISSUE_BODY" | grep -oP '(?:^|\n)(?:--)?customer:\s*\K[^\r\n]+' | head -1 || echo "")
            CUSTOMER_LINK=$(echo "$ISSUE_BODY" | grep -oP '(?:^|\n)(?:--)?customer_link:\s*\K[^\r\n]+' | head -1 || echo "")
            SUPER_PASSWORD=$(echo "$ISSUE_BODY" | grep -oP '(?:^|\n)(?:--)?super_password:\s*\K[^\r\n]+' | head -1 || echo "")
            SLOGAN=$(echo "$ISSUE_BODY" | grep -oP '(?:^|\n)(?:--)?slogan:\s*\K[^\r\n]+' | head -1 || echo "")
            RENDEZVOUS_SERVER=$(echo "$ISSUE_BODY" | grep -oP '(?:^|\n)(?:--)?rendezvous_server:\s*\K[^\r\n]+' | head -1 || echo "")
            RS_PUB_KEY=$(echo "$ISSUE_BODY" | grep -oP '(?:^|\n)(?:--)?rs_pub_key:\s*\K[^\r\n]+' | head -1 || echo "")
            API_SERVER=$(echo "$ISSUE_BODY" | grep -oP '(?:^|\n)(?:--)?api_server:\s*\K[^\r\n]+' | head -1 || echo "")
            
            # 如果新格式没有找到，尝试旧格式
            if [ -z "$TAG" ]; then
              TAG=$(echo "$ISSUE_BODY" | grep -oP '--tag:\s*\K[^\r\n]+' | head -1 || echo "")
            fi
            if [ -z "$EMAIL" ]; then
              EMAIL=$(echo "$ISSUE_BODY" | grep -oP '--email:\s*\K[^\r\n]+' | head -1 || echo "")
            fi
            if [ -z "$CUSTOMER" ]; then
              CUSTOMER=$(echo "$ISSUE_BODY" | grep -oP '--customer:\s*\K[^\r\n]+' | head -1 || echo "")
            fi
            if [ -z "$CUSTOMER_LINK" ]; then
              CUSTOMER_LINK=$(echo "$ISSUE_BODY" | grep -oP '--customer_link:\s*\K[^\r\n]+' | head -1 || echo "")
            fi
            if [ -z "$SUPER_PASSWORD" ]; then
              SUPER_PASSWORD=$(echo "$ISSUE_BODY" | grep -oP '--super_password:\s*\K[^\r\n]+' | head -1 || echo "")
            fi
            if [ -z "$SLOGAN" ]; then
              SLOGAN=$(echo "$ISSUE_BODY" | grep -oP '--slogan:\s*\K[^\r\n]+' | head -1 || echo "")
            fi
            if [ -z "$RENDEZVOUS_SERVER" ]; then
              RENDEZVOUS_SERVER=$(echo "$ISSUE_BODY" | grep -oP '--rendezvous_server:\s*\K[^\r\n]+' | head -1 || echo "")
            fi
            if [ -z "$RS_PUB_KEY" ]; then
              RS_PUB_KEY=$(echo "$ISSUE_BODY" | grep -oP '--rs_pub_key:\s*\K[^\r\n]+' | head -1 || echo "")
            fi
            if [ -z "$API_SERVER" ]; then
              API_SERVER=$(echo "$ISSUE_BODY" | grep -oP '--api_server:\s*\K[^\r\n]+' | head -1 || echo "")
            fi
            
            # 调试输出提取的参数
            echo "Extracted parameters:"
            echo "TAG: '$TAG'"
            echo "EMAIL: '$EMAIL'"
            echo "CUSTOMER: '$CUSTOMER'"
            echo "CUSTOMER_LINK: '$CUSTOMER_LINK'"
            echo "SUPER_PASSWORD: '$SUPER_PASSWORD'"
            echo "SLOGAN: '$SLOGAN'"
            echo "RENDEZVOUS_SERVER: '$RENDEZVOUS_SERVER'"
            echo "RS_PUB_KEY: '$RS_PUB_KEY'"
            echo "API_SERVER: '$API_SERVER'"
          fi
          
          # 检查关键参数是否为空，如果为空则使用secrets兜底
          if [ -z "$RENDEZVOUS_SERVER" ] || [ -z "$RS_PUB_KEY" ]; then
            echo "Using secrets fallback for missing critical parameters"
            TAG="${TAG:-${{ secrets.DEFAULT_TAG }}}"
            EMAIL="${EMAIL:-${{ secrets.DEFAULT_EMAIL }}}"
            CUSTOMER="${CUSTOMER:-${{ secrets.DEFAULT_CUSTOMER }}}"
            CUSTOMER_LINK="${CUSTOMER_LINK:-${{ secrets.DEFAULT_CUSTOMER_LINK }}}"
            SUPER_PASSWORD="${SUPER_PASSWORD:-${{ secrets.DEFAULT_SUPER_PASSWORD }}}"
            SLOGAN="${SLOGAN:-${{ secrets.DEFAULT_SLOGAN }}}"
            RENDEZVOUS_SERVER="${RENDEZVOUS_SERVER:-${{ secrets.DEFAULT_RENDEZVOUS_SERVER }}}"
            RS_PUB_KEY="${RS_PUB_KEY:-${{ secrets.DEFAULT_RS_PUB_KEY }}}"
            API_SERVER="${API_SERVER:-${{ secrets.DEFAULT_API_SERVER }}}"
          fi
          
          # 生成初始JSON数据
          DATA=$(jq -c -n \
            --arg tag "$TAG" \
            --arg email "$EMAIL" \
            --arg customer "$CUSTOMER" \
            --arg customer_link "$CUSTOMER_LINK" \
            --arg super_password "$SUPER_PASSWORD" \
            --arg slogan "$SLOGAN" \
            --arg rendezvous_server "$RENDEZVOUS_SERVER" \
            --arg rs_pub_key "$RS_PUB_KEY" \
            --arg api_server "$API_SERVER" \
            '{tag: $tag, email: $email, customer: $customer, customer_link: $customer_link, super_password: $super_password, slogan: $slogan, rendezvous_server: $rendezvous_server, rs_pub_key: $rs_pub_key, api_server: $api_server}')
          
          # 存储输出
          echo "data=$DATA" >> $GITHUB_OUTPUT
          echo "trigger_type=$TRIGGER_TYPE" >> $GITHUB_OUTPUT
          echo "build_id=$BUILD_ID" >> $GITHUB_OUTPUT
      
      - name: Overwrite issue content
        if: github.event_name == 'issues'
        run: |
          # 创建清理后的issue内容，保留原始标题和标签
          CLEANED_BODY="## 构建请求已处理

          **构建参数：**
          - 标签: ${{ fromJson(steps.setup.outputs.data).tag }}
          - 客户: ${{ fromJson(steps.setup.outputs.data).customer }}
          - 标语: ${{ fromJson(steps.setup.outputs.data).slogan }}

          **状态：** 构建已启动
          **时间：** $(date '+%Y-%m-%d %H:%M:%S')

          ---
          *敏感信息已自动清理，原始参数已安全保存*"
          
          # 使用jq正确转义JSON
          JSON_PAYLOAD=$(jq -n --arg body "$CLEANED_BODY" '{"body": $body}')
          
          # 使用GitHub API更新issue
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
            -d "$JSON_PAYLOAD"
      
      - name: Verify dependencies
        run: echo "Checking system dependencies"
      
      - name: Generate config
        run: |
          # 在同一个job中访问数据
          echo "Trigger type: ${{ steps.setup.outputs.trigger_type }}"
          echo "Build ID: ${{ steps.setup.outputs.build_id }}"
          echo "Tag: ${{ fromJson(steps.setup.outputs.data).tag }}"
          echo "Customer: ${{ fromJson(steps.setup.outputs.data).customer }}"
          echo "Rendezvous Server: ${{ fromJson(steps.setup.outputs.data).rendezvous_server }}" 