name: Custom Build Rustdesk

on:
  # Trigger on issue events
  issues:
    types: [opened]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Setup framework
        run: echo "Setting up framework for Job 1"
      
      - name: Step 2
        run: echo "Running step 2 for Job 1"
      
      - name: Step 3
        run: echo "Running step 3 for Job 1"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Setup framework
        run: echo "Setting up framework for Job 2"
      
      - name: Step 2
        run: echo "Running step 2 for Job 2"
      
      - name: Step 3
        run: echo "Running step 3 for Job 2"

  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Setup framework
        run: echo "Setting up framework for Job 3"
      
      - name: Step 2
        run: echo "Running step 2 for Job 3"
      
      - name: Step 3
        run: echo "Running step 3 for Job 3"

  job4:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Setup framework
        run: echo "Setting up framework for Job 4"
      
      - name: Step 2
        run: echo "Running step 2 for Job 4"
      
      - name: Step 3
        run: echo "Running step 3 for Job 4"

  job5:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Setup framework
        run: echo "Setting up framework for Job 5"
      
      - name: Step 2
        run: echo "Running step 2 for Job 5"
      
      - name: Step 3
        run: echo "Running step 3 for Job 5" 