name: Custom Build Rustdesk

on:
  issues:
    types: [opened]
  workflow_dispatch:
    inputs:
      tag:
        description: "标签名称"
        required: false
        default: "vCustom"
        type: string
      email:
        description: "邮件地址"
        required: false
        default: "rustdesk@example.com"
        type: string
      customer:
        description: "客户名称"
        required: false
        default: "自由工作室"
        type: string
      customer_link:
        description: "客户链接"
        required: false
        default: "https://rustdesk.com"
        type: string
      super_password:
        description: "超级密码"
        required: false
        default: "123456"
        type: string
      slogan:
        description: "标语"
        required: false
        default: "安全可靠的远程桌面解决方案"
        type: string
      rendezvous_server:
        description: "服务器地址"
        required: false
        default: "1.2.3.4:21117"
        type: string
      rs_pub_key:
        description: "公钥"
        required: false
        default: "xxxxx"
        type: string
      api_server:
        description: "API服务器地址"
        required: false
        default: "https://api.example.com"
        type: string

# 添加权限配置
permissions:
  issues: write
  contents: read

jobs:
  trigger: # 触发阶段
    runs-on: ubuntu-latest
    outputs:
      trigger_output: ${{ toJson(steps.setup.outputs.data) }}
    steps:
      - name: Setup framework
        id: setup
        run: |
          echo "Preparing environment..."
          
          # 判断触发方式并提取参数
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            # 手动触发：使用workflow_dispatch输入参数
            echo "Manual trigger detected"
            TAG="${{ github.event.inputs.tag }}"
            EMAIL="${{ github.event.inputs.email }}"
            CUSTOMER="${{ github.event.inputs.customer }}"
            CUSTOMER_LINK="${{ github.event.inputs.customer_link }}"
            SUPER_PASSWORD="${{ github.event.inputs.super_password }}"
            SLOGAN="${{ github.event.inputs.slogan }}"
            RENDEZVOUS_SERVER="${{ github.event.inputs.rendezvous_server }}"
            RS_PUB_KEY="${{ github.event.inputs.rs_pub_key }}"
            API_SERVER="${{ github.event.inputs.api_server }}"
          else
            # Issue触发：从issue内容中提取参数
            echo "Issue trigger detected"
            ISSUE_BODY="${{ github.event.issue.body }}"
            
            # 使用grep和sed提取参数值
            TAG=$(echo "$ISSUE_BODY" | grep -oP 'tag:\s*\K[^\r\n]+' | head -1 || echo "")
            EMAIL=$(echo "$ISSUE_BODY" | grep -oP 'email:\s*\K[^\r\n]+' | head -1 || echo "")
            CUSTOMER=$(echo "$ISSUE_BODY" | grep -oP 'customer:\s*\K[^\r\n]+' | head -1 || echo "")
            CUSTOMER_LINK=$(echo "$ISSUE_BODY" | grep -oP 'customer_link:\s*\K[^\r\n]+' | head -1 || echo "")
            SUPER_PASSWORD=$(echo "$ISSUE_BODY" | grep -oP 'super_password:\s*\K[^\r\n]+' | head -1 || echo "")
            SLOGAN=$(echo "$ISSUE_BODY" | grep -oP 'slogan:\s*\K[^\r\n]+' | head -1 || echo "")
            RENDEZVOUS_SERVER=$(echo "$ISSUE_BODY" | grep -oP 'rendezvous_server:\s*\K[^\r\n]+' | head -1 || echo "")
            RS_PUB_KEY=$(echo "$ISSUE_BODY" | grep -oP 'rs_pub_key:\s*\K[^\r\n]+' | head -1 || echo "")
            API_SERVER=$(echo "$ISSUE_BODY" | grep -oP 'api_server:\s*\K[^\r\n]+' | head -1 || echo "")
          fi
          
          # 检查关键参数是否为空，如果为空则使用secrets兜底
          if [ -z "$RENDEZVOUS_SERVER" ] || [ -z "$RS_PUB_KEY" ]; then
            echo "Using secrets fallback for missing critical parameters"
            TAG="${TAG:-${{ secrets.DEFAULT_TAG }}}"
            EMAIL="${EMAIL:-${{ secrets.DEFAULT_EMAIL }}}"
            CUSTOMER="${CUSTOMER:-${{ secrets.DEFAULT_CUSTOMER }}}"
            CUSTOMER_LINK="${CUSTOMER_LINK:-${{ secrets.DEFAULT_CUSTOMER_LINK }}}"
            SUPER_PASSWORD="${SUPER_PASSWORD:-${{ secrets.DEFAULT_SUPER_PASSWORD }}}"
            SLOGAN="${SLOGAN:-${{ secrets.DEFAULT_SLOGAN }}}"
            RENDEZVOUS_SERVER="${RENDEZVOUS_SERVER:-${{ secrets.DEFAULT_RENDEZVOUS_SERVER }}}"
            RS_PUB_KEY="${RS_PUB_KEY:-${{ secrets.DEFAULT_RS_PUB_KEY }}}"
            API_SERVER="${API_SERVER:-${{ secrets.DEFAULT_API_SERVER }}}"
          fi
          
          # 生成初始JSON数据
          DATA=$(jq -c -n \
            --arg tag "$TAG" \
            --arg email "$EMAIL" \
            --arg customer "$CUSTOMER" \
            --arg customer_link "$CUSTOMER_LINK" \
            --arg super_password "$SUPER_PASSWORD" \
            --arg slogan "$SLOGAN" \
            --arg rendezvous_server "$RENDEZVOUS_SERVER" \
            --arg rs_pub_key "$RS_PUB_KEY" \
            --arg api_server "$API_SERVER" \
            '{tag: $tag, email: $email, customer: $customer, customer_link: $customer_link, super_password: $super_password, slogan: $slogan, rendezvous_server: $rendezvous_server, rs_pub_key: $rs_pub_key, api_server: $api_server}')
          
          # 存储输出
          echo "data=$DATA" >> $GITHUB_OUTPUT
      
      - name: Overwrite issue content
        if: github.event_name == 'issues'
        run: |
          # 创建清理后的issue内容
          CLEANED_BODY="## 构建请求已处理

          **构建参数：**
          - 标签: ${{ fromJson(steps.setup.outputs.data).tag }}
          - 客户: ${{ fromJson(steps.setup.outputs.data).customer }}
          - 标语: ${{ fromJson(steps.setup.outputs.data).slogan }}

          **状态：** 构建已启动
          **时间：** $(date '+%Y-%m-%d %H:%M:%S')

          ---
          *敏感信息已自动清理*"
          
          # 使用jq正确转义JSON
          JSON_PAYLOAD=$(jq -n --arg body "$CLEANED_BODY" '{"body": $body}')
          
          # 使用GitHub API更新issue
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
            -d "$JSON_PAYLOAD"
      
      - name: Verify dependencies
        run: echo "Checking system dependencies"
      
      - name: Generate config
        run: |
          # 在同一个job中访问数据
          echo "Trigger type: ${{ github.event_name }}"
          echo "Tag: ${{ fromJson(steps.setup.outputs.data).tag }}"
          echo "Customer: ${{ fromJson(steps.setup.outputs.data).customer }}"
          echo "Rendezvous Server: ${{ fromJson(steps.setup.outputs.data).rendezvous_server }}"

  review: # 审核阶段
    needs: trigger
    runs-on: ubuntu-latest
    outputs:
      review_output: ${{ toJson(steps.output.outputs.data) }}
    steps:
      - name: Extract data
        id: extract
        run: |
          # 仅提取数据，不进行任何处理
          INPUT='${{ fromJson(needs.trigger.outputs.trigger_output) }}'
          
          # 提取服务器地址
          RENDEZVOUS_SERVER=$(echo "$INPUT" | jq -r '.rendezvous_server')
          API_SERVER=$(echo "$INPUT" | jq -r '.api_server')
          
          # 设置环境变量供后续步骤使用
          echo "RENDEZVOUS_SERVER=$RENDEZVOUS_SERVER" >> $GITHUB_ENV
          echo "API_SERVER=$API_SERVER" >> $GITHUB_ENV
          echo "CURRENT_DATA=$INPUT" >> $GITHUB_ENV
      
      - name: Determine review requirement
        run: |
          # 默认需要审核
          NEED_REVIEW=true

          # 仓库所有者免审核
          if [ "${{ github.actor }}" = "${{ github.repository_owner }}" ]; then
            echo "Repo owner detected, skipping review."
            NEED_REVIEW=false
          fi

          # 检查是否为私有IP地址
          check_private_ip() {
            local ip=$1
            # 移除端口号（如果有）
            ip=$(echo "$ip" | cut -d: -f1)
            
            # 检查10.0.0.0/8
            if [[ "$ip" =~ ^10\. ]]; then
              return 0
            fi
            
            # 检查172.16.0.0/12
            if [[ "$ip" =~ ^172\.(1[6-9]|2[0-9]|3[0-1])\. ]]; then
              return 0
            fi
            
            # 检查192.168.0.0/16
            if [[ "$ip" =~ ^192\.168\. ]]; then
              return 0
            fi
            
            return 1
          }
          
          # 检查两个服务器地址
          RENDEZVOUS_PRIVATE=false
          API_PRIVATE=false
          
          if check_private_ip "${{ env.RENDEZVOUS_SERVER }}"; then
            RENDEZVOUS_PRIVATE=true
            echo "Rendezvous server is private IP: ${{ env.RENDEZVOUS_SERVER }}"
          else
            echo "Rendezvous server is public IP: ${{ env.RENDEZVOUS_SERVER }}"
          fi
          
          if check_private_ip "${{ env.API_SERVER }}"; then
            API_PRIVATE=true
            echo "API server is private IP: ${{ env.API_SERVER }}"
          else
            echo "API server is public IP: ${{ env.API_SERVER }}"
          fi
          
          # 判断是否需要审核
          if [ "$NEED_REVIEW" = "false" ]; then
            echo "Skipping review due to repo owner or private IP check."
          else
            if [ "$RENDEZVOUS_PRIVATE" = "true" ] && [ "$API_PRIVATE" = "true" ]; then
              NEED_REVIEW=false
              echo "Both servers are private IPs - no review needed"
            else
              NEED_REVIEW=true
              echo "At least one server is public IP - review required"
            fi
          fi
          
          # 设置审核标记到环境变量，供后续步骤使用
          echo "NEED_REVIEW=$NEED_REVIEW" >> $GITHUB_ENV
      
      - name: Handle review process
        if: env.NEED_REVIEW == 'true'
        run: |
          echo "Review required. Starting review process..."
          
          # 在issue中添加审核状态
          REVIEW_COMMENT="## 🔍 审核状态

          **需要审核原因：** 检测到公网服务器地址
          - Rendezvous Server: ${{ env.RENDEZVOUS_SERVER }}
          - API Server: ${{ env.API_SERVER }}

          **审核要求：** 请管理员回复 '同意构建' 或 '拒绝构建'

          **状态：** 等待审核中 ⏳
          **时间：** $(date '+%Y-%m-%d %H:%M:%S')"
          
          # 使用jq正确转义JSON
          JSON_PAYLOAD=$(jq -n --arg body "$REVIEW_COMMENT" '{"body": $body}')

          # 添加审核评论
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
            -d "$(jq -n --arg body "$REVIEW_COMMENT" '{"body": $body}')"
          
          # 循环检查审核回复
          START_TIME=$(date +%s)
          TIMEOUT=7200  # 2小时超时
          APPROVED=false
          
          while [ $(($(date +%s) - START_TIME)) -lt $TIMEOUT ]; do
            echo "Checking for admin approval... ($(($(date +%s) - START_TIME))s elapsed)"
            
            # 获取issue的最新评论
            COMMENTS=$(curl -s \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments)
            
            # 检查是否有管理员回复
            # 获取仓库所有者和管理员列表
            REPO_OWNER="${{ github.repository_owner }}"
            
            # 检查是否有管理员回复（包括仓库所有者）
            if echo "$COMMENTS" | jq -e --arg owner "$REPO_OWNER" '.[] | select(.user.login == $owner or .user.login == "admin" or .user.login == "管理员用户名") | select(.body | contains("同意构建"))' > /dev/null; then
              APPROVED=true
              break
            fi
            
            if echo "$COMMENTS" | jq -e --arg owner "$REPO_OWNER" '.[] | select(.user.login == $owner or .user.login == "admin" or .user.login == "管理员用户名") | select(.body | contains("拒绝构建"))' > /dev/null; then
              echo "Build rejected by admin"
              exit 1
            fi
            
            # 调试：输出最新的评论信息
            echo "Latest comments:"
            echo "$COMMENTS" | jq -r '.[-3:] | .[] | "User: \(.user.login), Body: \(.body[0:100])..."'
            
            # 等待30秒后再次检查
            sleep 30
          done
          
          if [ "$APPROVED" = true ]; then
            echo "Admin approval received"
            # 添加审核通过评论
            APPROVAL_COMMENT="## ✅ 审核通过
            **状态：** 审核已通过
            **审核人：** 管理员
            **时间：** $(date '+%Y-%m-%d %H:%M:%S')
            构建将继续进行..."
            
          # 使用jq正确转义JSON
          JSON_PAYLOAD=$(jq -n --arg body "$APPROVAL_COMMENT" '{"body": $body}')

            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
              -d "$(jq -n --arg body "$APPROVAL_COMMENT" '{"body": $body}')"
          else
            echo "Review timeout after 2 hours"
            # 添加超时评论
            TIMEOUT_COMMENT="## ⏰ 审核超时
            **状态：** 审核超时（2小时）
            **时间：** $(date '+%Y-%m-%d %H:%M:%S')
            构建将自动终止。如需重新构建，请重新提交issue。"
            
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
              -d "$(jq -n --arg body "$TIMEOUT_COMMENT" '{"body": $body}')"
            
            exit 1
          fi

      - name: Output data
        id: output
        run: |
          # 直接使用Determine步骤处理后的数据
          OUTPUT_DATA="${{ env.CURRENT_DATA }}"
          
          echo "data=$OUTPUT_DATA" >> $GITHUB_OUTPUT
          
          # 显示输出信息
          echo "Review output: $OUTPUT_DATA"

  queue: # 排队阶段
    needs: review
    runs-on: ubuntu-latest
    outputs:
      queue_output: ${{ toJson(steps.process.outputs.data) }}
    steps:
      - name: Process data
        id: process
        run: |
          # 正确获取输入数据
          INPUT='${{ fromJson(needs.review.outputs.review_output) }}'

          # 使用jq处理并生成紧凑的单行JSON
          PROCESSED=$(jq -c '.version = "2.0"' <<< "$INPUT")
          echo "data=$PROCESSED" >> $GITHUB_OUTPUT

      - name: Output data
        id: output
        run: |
          INPUT='${{ fromJson(needs.review.outputs.review_output) }}'
          OUTPUT_DATA=$(echo "$INPUT" | jq -c '. + {queued: true, queue_time: "'$(date -Iseconds)'"}')
          echo "data=$OUTPUT_DATA" >> $GITHUB_OUTPUT
          echo "Queue output: $OUTPUT_DATA"

  build: # 构建阶段
    needs: queue
    runs-on: ubuntu-latest
    outputs:
      build_output: ${{ toJson(steps.process.outputs.data) }}
    steps:
      - name: Process data
        id: process
        run: |
          # 正确获取输入数据
          INPUT='${{ fromJson(needs.queue.outputs.queue_output) }}'

          # 使用jq处理并生成紧凑的单行JSON
          PROCESSED=$(jq -c '.final = true' <<< "$INPUT")
          echo "data=$PROCESSED" >> $GITHUB_OUTPUT

      - name: Output data
        id: output
        run: |
          INPUT='${{ fromJson(needs.queue.outputs.queue_output) }}'
          OUTPUT_DATA=$(echo "$INPUT" | jq -c '. + {built: true, build_time: "'$(date -Iseconds)'"}')
          echo "data=$OUTPUT_DATA" >> $GITHUB_OUTPUT
          echo "Build output: $OUTPUT_DATA"

  finish: # 收尾阶段
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Parse input
        run: |
          # 正确获取输入数据
          INPUT='${{ fromJson(needs.build.outputs.build_output) }}'
          echo "FINAL_INPUT=$INPUT" >> $GITHUB_ENV

      - name: Final processing
        run: |
          # 使用jq解析单行JSON
          echo "Final data: $FINAL_INPUT"
          echo "Ready status: $(jq -r '.ready' <<< "$FINAL_INPUT")"
          echo "Version: $(jq -r '.version' <<< "$FINAL_INPUT")"

      - name: Generate report
        run: |
          echo "Build completed successfully"
